-- Active: 1729722794341@@127.0.0.1@1433@SERRA@dbo
-- Faça uma lista, no banco de dados SERRA, que mostre a descrição da seção e nome do produto, classificado pela descrição da seção e depois (em segundo nível) pelo nome do produto.

SELECT SEC_DESCRICAO, PRO_NOME
FROM "SECAO", "PRODUTOS"
WHERE "SEC_CODIGO" = "PRO_SECAO"
ORDER BY 1,2;

SELECT S.SEC_DESCRICAO, P.PRO_NOME
FROM "SECAO" AS S
INNER JOIN "PRODUTOS" AS P
ON P."PRO_SECAO" = S."SEC_CODIGO"
ORDER BY 1,2;

-- LEFT JOIN
SELECT  S.SEC_DESCRICAO AS SECAO,
        P.PRO_NOME AS PRODUTO
FROM SECAO AS S
LEFT JOIN PRODUTOS AS P
ON S.SEC_CODIGO = P.PRO_SECAO
ORDER BY 2;

-- RIGHT JOIN
SELECT  S.SEC_DESCRICAO AS SECAO,
        P.PRO_NOME AS PRODUTO
FROM SECAO AS S
RIGHT JOIN PRODUTOS AS P
ON S.SEC_CODIGO = P.PRO_SECAO
ORDER BY 1,2;