-- Active: 1729722794341@@127.0.0.1@1433@SERRA@dbo
-- CRIAR TABELA COM CHAVE PRIMÁRIA
CREATE TABLE SECAO(
    SEC_CODIGO SMALLINT,
    SEC_DESCRICAO VARCHAR(25),
    PRIMARY KEY(SEC_CODIGO)
);

-- CRIAR TABELA COM CHAVE ESTRANGEIRA
CREATE TABLE PRODUTOS(
    PRO_CODIGO INTEGER NOT NULL,
    PRO_NOME VARCHAR(50),
    PRO_DATA_CADASTRO DATE DEFAULT GETDATE(),
    PRO_PRECO_ATACADO MONEY DEFAULT 0 CHECK(PRO_PRECO_ATACADO >= 0),
    PRO_SECAO SMALLINT,
    PRIMARY KEY(PRO_CODIGO),
    FOREIGN KEY(PRO_SECAO) REFERENCES SECAO(SEC_CODIGO)
);

-- DECLARAÇÃO DE VARIÁVEIS E FUNÇÕES DE TEMPO
-- DECLARE @DATE DATE = GETDATE()
-- DECLARE @TIME TIME = GETDATE()
-- DECLARE @DATETIME DATETIME = GETDATE()
-- DECLARE @DATETIME2 DATETIME2(4) = GETDATE()
-- DECLARE @SMALLDATETIME SMALLDATETIME = GETDATE()

-- SELECT  @DATETIME AS DATETIME,
--         @DATETIME2 AS DATETIME2,
--         @SMALLDATETIME AS SMALLDATETIME,
--         @DATE AS DATE,
--         @TIME AS TIME

-- ALTER TABLE
ALTER TABLE ALUNOS
ALTER COLUMN NOME VARCHAR(50) NOT NULL;

--sp_rename 'NomeTabela.NomeColunaAntigo', 'NovoNomeColuna', 'COLUMN';
sp_rename 'tbl_livros.Nome_Livro', 'Titulo_Livro', 'COLUMN';

ALTER TABLE ALUNOS
ADD EMAIL VARCHAR(30);

ALTER TABLE ALUNOS
DROP COLUMN EMAIL;

-- INSERIR DADOS
INSERT INTO ALUNOS (CODIGO, NOME, DTNASC, ENDERECO)
VALUES (1, 'MARIA', '1999-04-02', 'AV. ALMIRANTE BARROSO 1550');

-- UPDATE
UPDATE ALUNO
SET ENDERECO = 'AV. NAZARE 1212';

UPDATE ALUNO
SET ENDERECO = 'AV NAZARE 1212'
WHERE NOME = 'MARIA DAS DORES';

-- DELETE
DELETE FROM ALUNOS
WHERE CODIGO = '123';
