-- CORRENTISTAS - 04-10-2024

-- 01
SELECT A.Nome AS 'Agencia', C.UF, C.Cidade, C.Nome 
FROM Agencia A
INNER JOIN Corr C
ON A.Num_Agencia = C.Agencia
WHERE C.Nome LIKE '%SILVA%' AND C.UF != '' AND C.Cidade != ''
ORDER BY 1,2,3,4;

-- 04
SELECT	NASC,
		SUBSTRING(NASC, 1,2) AS DIA,
		SUBSTRING(NASC, 4,2) AS MES,
		SUBSTRING(NASC, 7,4) AS ANO
FROM CORR

--

SELECT	NOME,
		SEXO,
		NASC,
		SUBSTRING(NASC, 1,2) AS DIA,
		SUBSTRING(NASC, 4,2) AS MES,
		SUBSTRING(NASC, 7,4) AS ANO
FROM CORR
WHERE SEXO LIKE 'F' AND SUBSTRING(NASC, 7,4) > 2000;

-- 08
SELECT DISTINCT ESTCIV
FROM Corr

SELECT DISTINCT ESTCIV, NOME
FROM Corr
WHERE ESTCIV = ''

SELECT ESTCIV, NOME
FROM Corr
WHERE ESTCIV NOT IN ('U', 'C', 'O', 'V', 'S')

-- 09

UPDATE CORR
SET SEXO = 'O'
WHERE SEXO LIKE ''

UPDATE CORR
SET ESTCIV = 'P'
WHERE ESTCIV LIKE ''

-- 10

SELECT *
FROM CORR
WHERE SEXO = 'M' AND NOME LIKE '[M-R]%'
ORDER BY NOME

-- SERRA - 04-10-2024

-- 03
SELECT PRO_CODIGO AS 'CODIGO', PRO_NOME AS 'NOME', PRO_EST_ATUAL_LOJA AS 'ESTOQUE', PRO_PRECO_VAREJO AS 'PRECO', PRO_EST_ATUAL_LOJA * PRO_PRECO_VAREJO AS 'TOTAL'
FROM PRODUTOS
WHERE PRO_EST_ATUAL_LOJA > 0 AND PRO_PRECO_VAREJO > 0
ORDER BY 5;

-- 05
SELECT TOP 10 PRO_NOME AS 'NOME', PRO_EST_ATUAL_LOJA AS 'ESTOQUE', PRO_PRECO_VAREJO AS 'PRECO VAREJO', PRO_PRECO_PROMOCAO AS 'PRECO PROMOCAO', (PRO_EST_ATUAL_LOJA * PRO_PRECO_VAREJO) AS 'TOTAL'
FROM PRODUTOS
WHERE PRO_EST_ATUAL_DEP > 0 AND PRO_PRECO_VAREJO > 0
ORDER BY 5 DESC;

-- 06
SELECT PRO_NOME AS 'NOME', PRO_PRECO_VAREJO AS 'PRECO', SEC_DESCRICAO AS 'DESCRICAO'
FROM PRODUTOS, SECAO
WHERE SEC_CODIGO = PRO_SECAO AND SEC_DESCRICAO LIKE 'BOMBA THEBE' AND PRO_PRECO_VAREJO > 0
ORDER BY 2 DESC

-- 07
SELECT AVG(PRO_PRECO_VAREJO)
FROM PRODUTOS
ORDER BY 1 DESC

SELECT UPPER(SEC_DESCRICAO) AS DESCRI��O, UPPER(PRO_NOME) AS PRODUTO
FROM SECAO, PRODUTOS
WHERE SEC_CODIGO = PRO_SECAO
ORDER BY 1,2;


SELECT UPPER(SEC_DESCRICAO) AS DESCRI��O, UPPER(PRO_NOME) AS PRODUTO
FROM SECAO
INNER JOIN PRODUTOS
ON SEC_CODIGO = PRO_SECAO
ORDER BY 1,2;

SELECT UPPER(SEC_DESCRICAO) AS DESCRI��O, UPPER(PRO_NOME) AS PRODUTO
FROM SECAO
LEFT JOIN PRODUTOS
ON SEC_CODIGO = PRO_SECAO
ORDER BY 1,2;